### ISSUE TITLE
Import statement throws an error in the index.jsp within msal4j-servelt-auth

### ISSUE THREAD

**Issue by ttfo** [Azure-Samples/ms-identity-java-servlet-webapp-authentication#6]
Import statement throws an error in the index.jsp within msal4j-servelt-auth
It should be
`<%@ page import="com.microsoft.azuresamples.msal4j.*" %>`
instead of the current one

**Comment by idg-sam** [comment]
Thanks, I will fix it asap.

**Comment by idg-sam** [comment]
Fixed in [this commit](https://github.com/Azure-Samples/ms-identity-java-servlet-webapp-authentication/commit/9fda241aa4569b8fefa3eb7cf37c13e4a94c34b9)
